services:

  quiz-nginx-dev:
    image: nginx:alpine
    container_name: nginx-proxy-dev
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles:
      - "dev"

  quiz-postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: -c 'max_connections=500'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Moscow
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 45s
      test: pg_isready -U postgres
      timeout: 10s
    ports:
      - "6000:5432"
    restart: unless-stopped
    volumes:
      - ./postgres/postgrespg-init-db.sql:/docker-entrypoint-initdb.d/postgres-init.sql:rw
      - quiz-pgdata:/var/lib/postgresql/18/docker:rw
    networks:
      - nginx-le-network

  quiz-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://quiz-postgres:5432/quiz
      spring.datasource.password: postgres
      spring.datasource.username: postgres
      server.servlet.context-path: /api/quiz
      server.max-http-request-header-size: 10MB
      server.tomcat.max-http-post-size: 10MB
      spring.servlet.multipart.max-file-size: 10MB
      spring.servlet.multipart.max-request-size: 10MB
    restart: unless-stopped
    networks:
      - nginx-le-network

  quiz-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - nginx-le-network

volumes:
  quiz-pgdata:

networks:
  nginx-le-network:
    external: true