services:

  nginx-dev:
    image: nginx:alpine
    container_name: nginx-proxy-dev
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "9090:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ "dev" ]

  nginx-prod:
    image: nginx:alpine
    container_name: nginx-proxy-prod
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "9090:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: [ "prod" ]

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    command: -c 'max_connections=500'
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Moscow
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 45s
      test: pg_isready -U postgres
      timeout: 10s
    ports:
      - "6000:5432"
    restart: unless-stopped
    volumes:
      - ./postgres/pg-init-db.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - pgdata:/var/lib/postgresql/18/docker:rw

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      server.servlet.context-path: /api/quiz
    restart: unless-stopped

volumes:
  pgdata: